// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SpecFlowNUnitDemo.Features
{
    using TechTalk.SpecFlow;
    using Autofac;
    using Autofac.Configuration;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("ContactUs")]
    public partial class ContactUsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private OpenQA.Selenium.IWebDriver driver;
        
        private IContainer container;
        
#line 1 "ContactUs.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUp()]
        public virtual void FeatureSetup()
        {
            var builder = new ContainerBuilder();
            builder.RegisterModule(new ConfigurationSettingsReader());
            this.container = builder.Build();
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "ContactUs", "\tNavigate to Contact Us page\r\n\tFill in the form\r\n\tSubmit the form", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDown()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
            try { System.Threading.Thread.Sleep(50); this.driver.Quit(); } catch (System.Exception) {}
            this.driver = null;
            ScenarioContext.Current.Remove("Driver");
            ScenarioContext.Current.Remove("Container");
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            if(this.driver != null)
                ScenarioContext.Current.Add("Driver", this.driver);
            if(this.container != null)
                ScenarioContext.Current.Add("Container", this.container);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        private void InitializeSelenium(string browser)
        {
            this.driver = this.container.ResolveNamed<OpenQA.Selenium.IWebDriver>(browser);
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Location is mandotary field By Imperative")]
        [NUnit.Framework.TestCaseAttribute("Chrome", Category="Chrome", TestName="LocationIsMandotaryFieldByImperative on Chrome")]
        [NUnit.Framework.TestCaseAttribute("Firefox", Category="Firefox", TestName="LocationIsMandotaryFieldByImperative on Firefox")]
        public virtual void LocationIsMandotaryFieldByImperative(string browser)
        {
            InitializeSelenium(browser);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Location is mandotary field By Imperative", new string[] {
                        "Browser:Chrome",
                        "Browser:Firefox"});
#line 8
this.ScenarioSetup(scenarioInfo);
#line 9
 testRunner.Given("I am at the Home Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 10
 testRunner.And("I navigate to ContactUs Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.When("I fill in First Name as Emily", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 12
 testRunner.And("I fill in Last Name as West", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
 testRunner.And("I fill in Job Title as Test Analyst", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
 testRunner.And("I fill in Organisation as Planit", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 15
 testRunner.And("I fill in Phone as 0211569987", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 16
 testRunner.And("I fill in Email as test@test.com", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 17
 testRunner.And("I press Submit Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 18
 testRunner.Then("I can see Please enter your Location message display", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Location is mandotary field By Declarative")]
        [NUnit.Framework.TestCaseAttribute("Chrome", Category="Chrome", TestName="LocationIsMandotaryFieldByDeclarative on Chrome")]
        [NUnit.Framework.TestCaseAttribute("Firefox", Category="Firefox", TestName="LocationIsMandotaryFieldByDeclarative on Firefox")]
        public virtual void LocationIsMandotaryFieldByDeclarative(string browser)
        {
            InitializeSelenium(browser);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Location is mandotary field By Declarative", new string[] {
                        "Browser:Chrome",
                        "Browser:Firefox"});
#line 22
this.ScenarioSetup(scenarioInfo);
#line 23
 testRunner.Given("I am at the Home Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 24
 testRunner.And("I navigate to ContactUs Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 25
 testRunner.When("I Fill the contact information form with correct information", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 26
 testRunner.And("I press Submit Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 27
 testRunner.Then("I can see error message display", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Location is mandotary field with Data Driven")]
        [NUnit.Framework.TestCaseAttribute("Chrome", Category="Chrome", TestName="LocationIsMandotaryFieldWithDataDriven on Chrome")]
        [NUnit.Framework.TestCaseAttribute("Firefox", Category="Firefox", TestName="LocationIsMandotaryFieldWithDataDriven on Firefox")]
        public virtual void LocationIsMandotaryFieldWithDataDriven(string browser)
        {
            InitializeSelenium(browser);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Location is mandotary field with Data Driven", new string[] {
                        "Browser:Chrome",
                        "Browser:Firefox"});
#line 31
this.ScenarioSetup(scenarioInfo);
#line 32
 testRunner.Given("I am at the Home Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 33
 testRunner.And("I navigate to ContactUs Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "firstname",
                        "lastname",
                        "jobtitle",
                        "organisation",
                        "phone",
                        "email"});
            table1.AddRow(new string[] {
                        "Helen",
                        "West",
                        "Test Analyst",
                        "Planit",
                        "0210581977",
                        "lyi@planittesting.com"});
#line 34
 testRunner.When("I Fill the contact information form with", ((string)(null)), table1, "When ");
#line 37
 testRunner.And("I press Submit Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 38
 testRunner.Then("I can see error message display", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Successfuly to set failure status in test report")]
        [NUnit.Framework.TestCaseAttribute("Chrome", Category="Chrome", TestName="SuccessfulyToSetFailureStatusInTestReport on Chrome")]
        public virtual void SuccessfulyToSetFailureStatusInTestReport(string browser)
        {
            InitializeSelenium(browser);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Successfuly to set failure status in test report", new string[] {
                        "Browser:Chrome"});
#line 41
this.ScenarioSetup(scenarioInfo);
#line 42
 testRunner.Given("I am at the Home Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 43
 testRunner.And("I navigate to ContactUs Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "firstname",
                        "lastname",
                        "jobtitle",
                        "organisation",
                        "phone",
                        "email"});
            table2.AddRow(new string[] {
                        "Helen",
                        "West",
                        "Test Analyst",
                        "Planit",
                        "0210581977",
                        "lyi@planittesting.com"});
#line 44
 testRunner.When("I Fill the contact information form with", ((string)(null)), table2, "When ");
#line 47
 testRunner.And("I press Submit Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 48
 testRunner.Then("I can see it successfully submit the contact information", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Location is mandotary field with Pending")]
        [NUnit.Framework.TestCaseAttribute("Chrome", Category="Chrome", TestName="LocationIsMandotaryFieldWithPending on Chrome")]
        public virtual void LocationIsMandotaryFieldWithPending(string browser)
        {
            InitializeSelenium(browser);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Location is mandotary field with Pending", new string[] {
                        "Browser:Chrome"});
#line 51
this.ScenarioSetup(scenarioInfo);
#line 52
 testRunner.Given("I am at the Home Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 53
 testRunner.And("I navigate to ContactUs Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 54
 testRunner.When("I want to try pending status in test report", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 55
 testRunner.Then("I can see the pending result", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
